a3 done
m-119/PY111-2020-1 pull request #4
Opened 2020-05-30 18:54 UTC by m-119

Выполнена реализация проверки скобок.
Более сложно можно было бы решить через стек:
> Если ( - стек растёт
> Если ) - стек уменьшается
> Если стек пустой, а требуется убрать - возвращаем False

2020-06-01 08:40 UTC, aeksei requested changes
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2020-06-01 08:40 UTC, aeksei commented on Tasks/a3_check_brackets.py
>      return False
инлайновый if

2020-06-15 03:41 UTC, m-119 commented
опечатался: вместо b1 a3

2020-06-22 06:07 UTC, aeksei approved these changes
Проверено

---

Если стоит **Changes approved**, то смело можно сливать ветки. 
И после слияния удалять ветку.

Всё что указано просто комментариями, носит рекомендательный характер.
Для моментов, которые нужно исправить, я буду запрашивать изменения.

2020-06-22 18:46 UTC, merged